// Utils/IngredientEmoji.swift
struct IngredientEmoji {

    // Ordered longest-keyword-first so specific terms (e.g. "spring onion")
    // match before shorter overlapping ones (e.g. "onion").
    private static let keywords: [(String, String)] = [
        ("spring onion",  "🌿"),
        ("bok choy",      "🥬"),
        ("bell pepper",   "🫑"),
        ("sweet potato",  "🍠"),
        ("oyster sauce",  "🫙"),
        ("cooking oil",   "🫚"),
        ("fish sauce",    "🫙"),
        ("soy sauce",     "🫙"),
        ("chili sauce",   "🫙"),
        ("strawberry",    "🍓"),
        ("blueberry",     "🫐"),
        ("pineapple",     "🍍"),
        ("watermelon",    "🍉"),
        ("eggplant",      "🍆"),
        ("aubergine",     "🍆"),
        ("cucumber",      "🥒"),
        ("capsicum",      "🫑"),
        ("broccoli",      "🥦"),
        ("mushroom",      "🍄"),
        ("cabbage",       "🥬"),
        ("avocado",       "🥑"),
        ("chicken",       "🍗"),
        ("sausage",       "🌭"),
        ("vinegar",       "🫙"),
        ("yogurt",        "🥛"),
        ("cheese",        "🧀"),
        ("butter",        "🧈"),
        ("shrimp",        "🦐"),
        ("salmon",        "🐟"),
        ("oyster",        "🦪"),
        ("noodle",        "🍜"),
        ("prawn",         "🦐"),
        ("lychee",        "🍈"),
        ("coffee",        "☕"),
        ("cherry",        "🍒"),
        ("potato",        "🥔"),
        ("tomato",        "🍅"),
        ("carrot",        "🥕"),
        ("onion",         "🧅"),
        ("garlic",        "🧄"),
        ("banana",        "🍌"),
        ("orange",        "🍊"),
        ("mango",         "🥭"),
        ("peach",         "🍑"),
        ("grape",         "🍇"),
        ("lemon",         "🍋"),
        ("bread",         "🍞"),
        ("flour",         "🌾"),
        ("sugar",         "🍬"),
        ("honey",         "🍯"),
        ("juice",         "🧃"),
        ("beans",         "🫘"),
        ("apple",         "🍎"),
        ("pasta",         "🍝"),
        ("pear",          "🍐"),
        ("kiwi",          "🥝"),
        ("corn",          "🌽"),
        ("tofu",          "🫘"),
        ("peas",          "🫛"),
        ("beef",          "🥩"),
        ("pork",          "🥩"),
        ("lamb",          "🥩"),
        ("duck",          "🍗"),
        ("steak",         "🥩"),
        ("tuna",          "🐟"),
        ("fish",          "🐟"),
        ("squid",         "🦑"),
        ("crab",          "🦀"),
        ("bacon",         "🥓"),
        ("milk",          "🥛"),
        ("cream",         "🥛"),
        ("rice",          "🍚"),
        ("oat",           "🌾"),
        ("egg",           "🥚"),
        ("ham",           "🥓"),
        ("ginger",        "🫚"),
        ("oil",           "🫚"),
        ("salt",          "🧂"),
        ("sauce",         "🫙"),
        ("paste",         "🫙"),
        ("stock",         "🫙"),
        ("broth",         "🫙"),
        ("canned",        "🥫"),
        ("water",         "💧"),
        ("lime",          "🍋"),
        ("melon",         "🍈"),
        ("tea",           "🍵"),
    ]

    // Pre-sorted longest-first so the array above can be written in readable order.
    private static let sortedKeywords: [(String, String)] =
        keywords.sorted { $0.0.count > $1.0.count }

    static func emoji(for name: String) -> String {
        let lower = name.lowercased()
        return sortedKeywords.first(where: { lower.contains($0.0) })?.1 ?? "🛒"
    }
}
